services:
  # DEVELOPMENT CONFIG HOT RELOAD (AIR)
  golang:
    image: go-air:1.26
    build:
      context: ./backend
      dockerfile: ../.docker/golang-air.Dockerfile
    container_name: golang_uas_mobile
    restart: unless-stopped
    # expose:
    #   - "8080"
    working_dir: /golang
    volumes:
      - ./backend:/golang
    environment:
      - ENV=development
    env_file:
      - .env
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      uas_mobile:
        ipv4_address: 172.20.0.10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.golang-service.entrypoints=web"
      - "traefik.http.routers.golang-service.rule=PathPrefix(`/api`)"
      - "traefik.http.services.golang-service.loadbalancer.server.port=${GO_PORT:-8080}"
      - "traefik.http.routers.golang-service.priority=10"

  db:
    image: "postgres:18-alpine"
    container_name: postgres_uas_mobile
    restart: unless-stopped
    ports:
      - "5432:5432"
    # expose:
    #   - "5432"
    environment:
      POSTGRES_DB: ${MAIN_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${MAIN_DB}"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 30s
    volumes:
      - ./.docker/postgres/sql:/docker-entrypoint-initdb.d
    networks:
      - uas_mobile

  # phpmyadmin:
  #   image: "phpmyadmin/phpmyadmin:latest"
  #   container_name: phpmyadmin_uas_mobile
  #   restart: unless-stopped
  #   # Ports sebaiknya dihapus jika tidak ingin akses langsung dari luar container
  #   # ports:
  #   #   - "80"
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     # PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #     PMA_ABSOLUTE_URI: http://localhost/pma/
  #   networks:
  #     - uas_mobile
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.pma-service.entrypoints=web"
  #     - "traefik.http.routers.pma-service.rule=PathPrefix(`/pma`)"
  #     - "traefik.http.middlewares.pma-slash.redirectregex.regex=^(.*)/pma$$"
  #     - "traefik.http.middlewares.pma-slash.redirectregex.replacement=$$1/pma/"
  #     - "traefik.http.middlewares.pma-strip.stripprefix.prefixes=/pma"
  #     - "traefik.http.routers.pma-service.middlewares=pma-slash,pma-strip"
  #     - "traefik.http.services.pma-service.loadbalancer.server.port=80"

  traefik:
    image: traefik:latest
    container_name: traefik_uas_mobile
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--accessLog=true"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - uas_mobile

networks:
  uas_mobile:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.1.0/24
